### PR TITLE
Update README.md for M1 config of installation of pygraphviz

### PR DESCRIPTION
**Pull request by samsruti-dash**
For M1 update for installing pygraphviz

### CODE REVIEW

**Comment by pires** [comment]
This worked for me, thank you! 👏🏻

**Review by pires — APPROVED** [review]
This worked for me, thank you! 👏🏻

**Comment by samsruti-dash** [comment]
Can we merge this?

**Comment by hbmartin** [comment]
I updated instructions before I noticed this, apologies.
Feel free to comment or re-open if you there's further improvements needed.
Thanks!

**Pull request closed without merging**
